"use client";

import React from "react";
import { motion } from "framer-motion";
import { ShieldCheck, TrendingUp, AlertTriangle, Scale, Target, Landmark, Compass, Award } from "lucide-react";
import { ResponsiveContainer, PieChart, Pie, Cell, Tooltip, Legend } from "recharts";
import { Scenario } from "./Simulator";

interface DashboardProps {
  activeScenario: Scenario;
}

export default function ExecutiveDashboard({ activeScenario }: DashboardProps) {
  // Score parameters
  const confidencePercent = activeScenario.confidence;
  const strokeDashoffset = 440 - (440 * confidencePercent) / 100;

  // Additional mock metrics based on scenario
  const metrics = [
    { name: "Emergency Fund Health", value: "Optimal (6 Mo)", status: "text-emerald-400", desc: "Adequate cash buffer established." },
    { name: "Retirement Readiness", value: `${activeScenario.cagr > 12 ? "Excellent" : "On Track"}`, status: "text-blue-400", desc: "SIP pacing supports target goal." },
    { name: "Tax Efficiency", value: "92% (High)", status: "text-cyan-400", desc: "ELSS + NPS structures leveraged." },
    { name: "Inflation Protection", value: "100% Protected", status: "text-emerald-400", desc: "Average return exceeds index rates." },
    { name: "Liquidity Score", value: "B+ (Healthy)", status: "text-indigo-400", desc: "Unrestricted assets exceed 45%." },
  ];

  return (
    <div id="dashboard" className="w-full max-w-6xl mx-auto py-24 px-6 md:px-12 select-none overflow-hidden">
      {/* Background Radial Glow */}
      <div className="absolute left-1/4 bottom-10 w-[400px] h-[400px] bg-emerald-500/5 blur-[120px] pointer-events-none"></div>

      {/* Header */}
      <div className="text-center max-w-3xl mx-auto mb-16">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-emerald-500/30 bg-emerald-500/10 text-emerald-400 text-xs font-semibold mb-4 tracking-wide uppercase">
          <Award className="w-3.5 h-3.5" /> Premium Executive Dashboard
        </div>
        <h2 className="text-4xl font-extrabold tracking-tight bg-gradient-to-r from-white via-slate-100 to-blue-400 bg-clip-text text-transparent">
          Executive Financial Dashboard
        </h2>
        <p className="text-slate-400 mt-4 text-base">
          Analyze institutional asset configurations, portfolio scores, and advisor trust parameters generated by the system.
        </p>
      </div>

      {/* Layout Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-stretch">
        
        {/* Left Widget Pane: Confidence & Basic Ratings (Col 4) */}
        <div className="lg:col-span-4 flex flex-col gap-6 justify-between p-6 rounded-2xl border border-white/10 bg-[#090d1f]/60 backdrop-blur-md">
          
          {/* Circular Gauge */}
          <div className="flex flex-col items-center justify-center text-center">
            <h3 className="text-xs font-mono font-bold text-slate-400 uppercase tracking-widest mb-6">
              Confidence Index
            </h3>
            
            <div className="relative w-44 h-44 flex items-center justify-center">
              {/* Outer SVG Track */}
              <svg className="w-full h-full transform -rotate-90">
                <circle
                  cx="88"
                  cy="88"
                  r="70"
                  className="stroke-slate-800 fill-none"
                  strokeWidth="10"
                />
                <motion.circle
                  cx="88"
                  cy="88"
                  r="70"
                  className="stroke-cyan-500 fill-none"
                  strokeWidth="10"
                  strokeDasharray="440"
                  initial={{ strokeDashoffset: 440 }}
                  animate={{ strokeDashoffset }}
                  transition={{ duration: 1.5, ease: "easeOut" }}
                  strokeLinecap="round"
                />
              </svg>
              
              <div className="absolute flex flex-col items-center justify-center">
                <span className="text-3xl font-bold font-mono text-white">{confidencePercent}%</span>
                <span className="text-[10px] text-slate-400 font-semibold uppercase mt-0.5">TRUST FACTOR</span>
              </div>
            </div>

            <p className="text-xs text-slate-400 leading-relaxed mt-6">
              Calculated dynamically based on agent alignment, backtest validity, and profile constraint validations.
            </p>
          </div>

          {/* Key Quick Stats */}
          <div className="border-t border-white/5 pt-6 space-y-4">
            <div className="flex items-center justify-between">
              <span className="text-xs text-slate-400 flex items-center gap-1.5">
                <TrendingUp className="w-3.5 h-3.5 text-cyan-400" /> Expected CAGR
              </span>
              <span className="text-sm font-bold text-emerald-400">{activeScenario.cagr}%</span>
            </div>

            <div className="flex items-center justify-between">
              <span className="text-xs text-slate-400 flex items-center gap-1.5">
                <ShieldCheck className="w-3.5 h-3.5 text-blue-400" /> Risk Rating
              </span>
              <span className={`text-sm font-bold ${
                activeScenario.risk === "Aggressive" 
                  ? "text-rose-400" 
                  : activeScenario.risk === "Moderate" 
                  ? "text-blue-400" 
                  : "text-emerald-400"
              }`}>{activeScenario.risk}</span>
            </div>
          </div>

        </div>

        {/* Center Widget Pane: Asset Allocations Donut (Col 5) */}
        <div className="lg:col-span-5 flex flex-col justify-between p-6 rounded-2xl border border-white/10 bg-[#090d1f]/60 backdrop-blur-md">
          <div>
            <h3 className="text-xs font-mono font-bold text-slate-400 uppercase tracking-widest mb-6">
              Asset Allocation Ratio
            </h3>

            {/* Recharts Pie Donut Chart */}
            <div className="w-full h-[220px]">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={activeScenario.allocations}
                    cx="50%"
                    cy="50%"
                    innerRadius={55}
                    outerRadius={80}
                    paddingAngle={3}
                    dataKey="value"
                  >
                    {activeScenario.allocations.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Pie>
                  <Tooltip
                    contentStyle={{
                      backgroundColor: "#070B18",
                      border: "1px solid rgba(255,255,255,0.1)",
                      borderRadius: "10px",
                      fontSize: "11px",
                    }}
                  />
                </PieChart>
              </ResponsiveContainer>
            </div>
          </div>

          {/* Allocation Legend */}
          <div className="grid grid-cols-3 gap-2 mt-4 pt-4 border-t border-white/5">
            {activeScenario.allocations.map((allocation, idx) => (
              <div key={idx} className="flex flex-col">
                <span className="text-[10px] text-slate-500 font-semibold uppercase flex items-center gap-1">
                  <span className="w-1.5 h-1.5 rounded-full shrink-0" style={{ backgroundColor: allocation.color }}></span>
                  {allocation.name}
                </span>
                <span className="text-xs font-bold text-white mt-0.5">{allocation.value}%</span>
              </div>
            ))}
          </div>

        </div>

        {/* Right Widget Pane: Scores Checklist (Col 3) */}
        <div className="lg:col-span-3 flex flex-col justify-between p-6 rounded-2xl border border-white/10 bg-[#090d1f]/60 backdrop-blur-md">
          <div>
            <h3 className="text-xs font-mono font-bold text-slate-400 uppercase tracking-widest mb-6">
              Advisory Scores
            </h3>
            
            <div className="space-y-4">
              {metrics.map((m, idx) => (
                <div key={idx} className="flex flex-col py-1.5 border-b border-white/5 last:border-b-0">
                  <div className="flex items-center justify-between">
                    <span className="text-xs text-slate-300 font-bold">{m.name}</span>
                    <span className={`text-[10px] font-mono font-bold ${m.status}`}>{m.value}</span>
                  </div>
                  <span className="text-[10px] text-slate-500 mt-0.5 leading-snug">{m.desc}</span>
                </div>
              ))}
            </div>
          </div>

          <div className="pt-4 border-t border-white/5 text-[10px] text-slate-500 font-mono text-center">
            LAST RATING COMPILED: TODAY
          </div>
        </div>

      </div>
    </div>
  );
}
